# Generated by Django 5.0.4 on 2024-05-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_alter_product_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
