# Generated by Django 5.0.4 on 2024-05-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecomapp', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product Name')),
                ('price', models.IntegerField()),
                ('category', models.IntegerField(choices=[(1, 'shoes'), (2, 'mobile'), (3, 'cloths')], verbose_name='Category')),
                ('pdetails', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is_Active')),
            ],
        ),
    ]
