# Generated by Django 5.0.4 on 2024-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.ImageField(upload_to='zimage'),
        ),
    ]
